### ISSUE TITLE
Responsive size testing for cleints

### ISSUE THREAD

**Issue by willforsyth** [samdbeckham/pattern-library-template#31]
I saw this nice feature that wouldn't be to hard to implement with a bit of time.

Add in some buttons / header nav that will resize the template from small to medium and large. So the clients / account handlers can click on the size and check the responsiveness of the page.

**Comment by samdbeckham** [comment]
Something like this? http://demo.patternlab.io/

I love the disco mode

**Comment by timhorwood** [comment]
Yo I still seem to get the emails for this?

@Sam, can you take a look when you get a min?

On Wed, May 20, 2015 at 9:46 AM, Sam Beckham <notifications@github.com>
wrote:

> Something like this? http://demo.patternlab.io/
>
> I love the disco mode
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/samdbeckham/pattern-library-template/issues/31#issuecomment-103813010>
> .
>



-- 
*Tim Horwood*

*FRONT END DEVELOPER*
*boxmodel digital media*
Toffee Factory
Lower Steenbergs Yard
Quayside, Ouseburn
Newcastle upon Tyne, NE1 2DF

*t: +44 (0)191 375 9116*

*e: tim@boxmodeldigital.com <tim@boxmodeldigital.com>w: boxmodeldigital.com
<http://boxmodeldigital.com/>*

*Boxmodel Digital Media Limited trading as Boxmodel, registered offices in
England at Boxmodel Digital Media, **Toffee Factory, Lower Steenbergs Yard,
Quayside, Ouseburn, Newcastle upon Tyne, NE1 2DF**, company registration
number 06929210.*

**Comment by samdbeckham** [comment]
You're watching the repo mate, you need to unwatch it. Top right corner next to star and fork.

**Comment by timhorwood** [comment]
So I was! Enjoy your pattern library related work fellas

On Wed, May 20, 2015 at 9:54 AM, Sam Beckham <notifications@github.com>
wrote:

> You're watching the repo mate, you need to unwatch it. Top right corner
> next to star and fork.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/samdbeckham/pattern-library-template/issues/31#issuecomment-103814839>
> .
>



-- 
*Tim Horwood*

*FRONT END DEVELOPER*
*boxmodel digital media*
Toffee Factory
Lower Steenbergs Yard
Quayside, Ouseburn
Newcastle upon Tyne, NE1 2DF

*t: +44 (0)191 375 9116*

*e: tim@boxmodeldigital.com <tim@boxmodeldigital.com>w: boxmodeldigital.com
<http://boxmodeldigital.com/>*

*Boxmodel Digital Media Limited trading as Boxmodel, registered offices in
England at Boxmodel Digital Media, **Toffee Factory, Lower Steenbergs Yard,
Quayside, Ouseburn, Newcastle upon Tyne, NE1 2DF**, company registration
number 06929210.*

**Comment by willforsyth** [comment]
Yeah thats exactly where I saw it :-)

**Comment by samdbeckham** [comment]
http://codepen.io/samdbeckham/pen/rVMNRE

There's the basics of it if you wanna take a crack at it? Needs some love but you get the idea.

**Comment by willforsyth** [comment]
ohh nice, I will look at implementing :-)
